language: csharp
dist: bionic
dotnet: 3.1
mono: none
git:
  depth: false
env:
  global:
    - SOLUTION=cba-NetCore.sln
    - Z3URL=https://github.com/Z3Prover/z3/releases/download/z3-4.8.4/z3-4.8.4.d6df51951f4c-x64-ubuntu-14.04.zip
  jobs:
    - CONFIGURATION=Debug
    - CONFIGURATION=Release

install:
  # Download a Z3 release, so that tests can eventually be run
  - wget ${Z3URL}
  - unzip z3*.zip
  - export PATH="$(find $PWD/z3* -name bin -type d):$PATH"

script:
  - git submodule update --init

  # Attach HEADs in submodules to appease GitVersion
  - git submodule foreach 'git branch -d master && git checkout -b master'

  # Build one configuration
  - dotnet build -c ${CONFIGURATION} ${SOLUTION}

  # Run regression tests
  - (cd test/regression && perl check.pl)

deploy:

  # Publish dotnet global tool on nuget.org
  - provider: script
    script: dotnet nuget push bin/${CONFIGURATION}/Corral*.nupkg -k ${NUGET_API_KEY} -s https://api.nuget.org/v3/index.json
    skip_cleanup: true
    on:
      all_branches: true
      condition: $CONFIGURATION = Release && $TRAVIS_TAG =~ ^v.*$

  # Publish GitHub release with dotnet global tool package
  - provider: releases
    name: $TRAVIS_TAG
    token:
      secure: Rvs8L97ieP/jpN//dX7iy8xATxtfm0Amjtu3LGUuYFnKx/tuxed3UdGZoXjnIoEiFTHPbxTScaIL2VM19hIvpWZAAu5eJrByw/+EMkj3nKhWtnr37QplhINB9HBKEokzeUn8gizyXOj3BuhdKfOxvO07oss9LLK9JDlbjlR+jgjin2ftBL8swzJZhzQ/ko+Xd5rIYbB5gTS3Utlq1HdjTrURhbQWb+WcY5CEN0E1OfgSZpCl09n6JWcKkhLo3tzcvQp7D3OYtWYvTHaHENc7klYsr7JRq/FnCy40ze29ZZ6a/n/hHhlXZKsBpMxMVAW61yiFPhJCht5rzSXjEX1kA3tpVbA4kzMN4MvgGcB4+gE8ucu5JQkvbvL0/9SQ08QPS9tmbNtfX92gh7sXEcljR1Anh1k36TLONZr4ZwwEqS2GIF0pbDz7ALJyYgou8NbykkzdIj34FquoxW2w0/Uf2/o62oXg+brftDJs0zbsKiFsP/2rrmadnMw4/Pzsza5GOt4hWsTw4YfEV/AebHSIM/lP2snycGn62OZyHdllzVmXwlrwOEbCCeiOwzQ85xnG4MLo/jwlCThF31W9fR6zHanxsETPenXZ+OCbhsGpQUtAaukvpYFXzi7h4Z5+bg09Yh6RF1psn3HdG5BrZLYRJsPFiRswzZlWupHGcAKxaNM=
    file_glob: true
    file: bin/${CONFIGURATION}/Corral*.nupkg
    skip_cleanup: true
    on:
      all_branches: true
      condition: $CONFIGURATION = Release && $TRAVIS_TAG =~ ^v.*$
